---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.circle::api
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.circle.api.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 1512
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDynamoDBTable
      Timeout: 60
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  UserDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "User"    
Outputs:
  CircleApi:
    Description: URL for application
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: CircleApi
